---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    username: "{{ user|default('adminlocal') }}"
  vars_files:
    - "vault/{{ username }}.yml"
    - credential.yml
  tasks:
  - name: Create error
    set_fact:
      errors: []
    run_once: true
  - name: Create report directory
    file:
      state: directory 
      path: reports
    run_once: true
  - name: Generate report errors
    include: "{{ item }}"
    with_fileglob:
      - validators/*.yml
  - name: Generate report
    template:
      src: templates/report.j2
      dest: reports/temp-report-{{ inventory_hostname }}.txt
  - name: Assemble report
    assemble:
      src: reports
      regexp: "^temp-report-.*.txt$"
      dest: reports/report.txt
    run_once: true
  - name: Delete temp files
    file:
      state: absent
      path: reports/temp-report-{{ inventory_hostname }}.txt
